# Generated by Django 3.0.5 on 2020-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0002_auto_20200510_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Имя изображения'),
        ),
    ]
