# Generated by Django 3.0.5 on 2020-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0004_auto_20200510_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='Site/apps/ecardb/static/image', verbose_name='Имя изображения'),
        ),
    ]
