# Generated by Django 3.0.5 on 2020-05-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0005_auto_20200510_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Имя изображения'),
        ),
    ]
