# Generated by Django 3.0.5 on 2020-05-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0008_delete_carinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info1', models.TextField(verbose_name='1')),
                ('info2', models.TextField(verbose_name='2')),
                ('info3', models.TextField(verbose_name='3')),
                ('info4', models.TextField(verbose_name='4')),
                ('info5', models.TextField(verbose_name='5')),
                ('info6', models.TextField(verbose_name='6')),
                ('info7', models.TextField(verbose_name='7')),
                ('info8', models.TextField(verbose_name='8')),
                ('info9', models.TextField(verbose_name='9')),
                ('info10', models.TextField(verbose_name='10')),
                ('info11', models.TextField(verbose_name='11')),
                ('info12', models.TextField(verbose_name='12')),
                ('info13', models.TextField(verbose_name='13')),
                ('info14', models.TextField(verbose_name='14')),
                ('info15', models.TextField(verbose_name='15')),
                ('info16', models.TextField(verbose_name='16')),
                ('info17', models.TextField(verbose_name='17')),
                ('info18', models.TextField(verbose_name='18')),
                ('info19', models.TextField(verbose_name='19')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecardb.Car')),
            ],
        ),
    ]
