# Generated by Django 3.0.5 on 2020-05-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0007_car_carinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarInfo',
        ),
    ]
