# Generated by Django 3.0.5 on 2020-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0011_car_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='info1',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info10',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info11',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info12',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info13',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info14',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info15',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info16',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info17',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info18',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info19',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info2',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info3',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info4',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info5',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info6',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info7',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info8',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='info9',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кузов 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кузов 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кузов 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кузов 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='drive_unit1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип привода 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='drive_unit2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип привода 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='drive_unit3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип привода 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='drive_unit4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип привода 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мощность 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мощность 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мощность 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мощность 4'),
        ),
    ]
