# Generated by Django 3.0.5 on 2020-05-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0012_auto_20200512_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='acceleration_time1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время разгона 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='acceleration_time2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время разгона 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='acceleration_time3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время разгона 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='acceleration_time4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время разгона 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='equipment1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комплектация 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='equipment2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комплектация 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='equipment3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комплектация 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='equipment4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комплектация 4'),
        ),
    ]
