# Generated by Django 3.0.5 on 2020-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0003_auto_20200510_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='ecardb/static/image', verbose_name='Имя изображения'),
        ),
    ]
