# Generated by Django 3.0.5 on 2020-05-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0009_carinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinfo',
            options={'verbose_name': 'Информация об электромобиле', 'verbose_name_plural': 'Информация об электромобилях'},
        ),
    ]
