# Generated by Django 3.0.5 on 2020-05-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecardb', '0013_auto_20200512_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='autopilot1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автопилот 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='autopilot2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автопилот 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='autopilot3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автопилот 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='autopilot4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автопилот 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body_dimensions1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты кузова 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body_dimensions2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты кузова 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body_dimensions3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты кузова 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='body_dimensions4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты кузова 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='class_car1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Класс 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='class_car2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Класс 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='class_car3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Класс 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='class_car4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Класс 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='clearance1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Клиренс 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='clearance2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Клиренс 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='clearance3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Клиренс 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='clearance4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Клиренс 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='electronic_assistants1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Электронные помощники 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='electronic_assistants2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Электронные помощники 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='electronic_assistants3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Электронные помощники 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='electronic_assistants4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Электронные помощники 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='max_speed1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная скорость 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='max_speed2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная скорость 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='max_speed3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная скорость 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='max_speed4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная скорость 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='nubmer_place1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Число мест 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='nubmer_place2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Число мест 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='nubmer_place3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Число мест 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='nubmer_place4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Число мест 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power_reserve1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Запас хода 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power_reserve2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Запас хода 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power_reserve3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Запас хода 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power_reserve4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Запас хода 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рулевое управление 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рулевое управление 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рулевое управление 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рулевое управление 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering_position1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Расположение руля 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering_position2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Расположение руля 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering_position3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Расположение руля 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='steering_position4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Расположение руля 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='torque1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Крутящий момент 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='torque2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Крутящий момент 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='torque3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Крутящий момент 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='torque4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Крутящий момент 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='transmission1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трансмиссия 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='transmission2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трансмиссия 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='transmission3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трансмиссия 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='transmission4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трансмиссия 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='trunk_volume1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Объем багажника 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='trunk_volume2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Объем багажника 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='trunk_volume3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Объем багажника 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='trunk_volume4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Объем багажника 4'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='weight1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Масса 1'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='weight2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Масса 2'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='weight3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Масса 3'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='weight4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Масса 4'),
        ),
    ]
